<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Company Page Progroup Authoring (Author_44faee_1_2_3_4_5</name>
   <tag></tag>
   <elementGuidId>2412bf7a-2573-45a5-82ec-fd7387743f25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cke_1_contents']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cke_wysiwyg_div cke_reset cke_enable_context_menu cke_editable cke_editable_themed cke_contents_ltr quark-editor-content qxml-webkit</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>hidefocus</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>contenteditable</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-multiline</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Rich Text Editor, xml_editor_panel</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>cke_77</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>proofreading</name>
      <type>Main</type>
      <value>on</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Company Page: Progroup​​​​​​​ Authoring (Author)Credit ViewWe maintain our Underperform on Progroup (PROGRP, Ba3/BB-). Our view on the name reflects the company's debt funded expansion plans during a weaker containerboard environment.  Authoring (Author)Business DescriptionProgroup AG is a corrugated board and linerboard manufacturer based in Landau, Germany. The company is majority owned by JH-Holding GmbH which is controlled by the Heindl family and therefore the founder of Progroup. The Group's core business comprises Propapier, which manufactures recycled linerboard at its two paper mills in Germany and Prowell, which produces corrugated medium at its eight corrugated board plants based in Germany, Poland, France, the UK and Czech Republic.Progroup caters primarily to family-owned box manufacturers serving various end-markets including consumer and industrial products such as processed and fresh food, agricultural products, beverages, industrial and consumer electronics, chemicals, and pharmaceuticals. Authoring (Author)Key Metrics€ mnY19Y18Y17Y16Y15Gross Leverage3.9x2.5x3.0x2.7x3.5xNet Leverage3.0x1.9x2.3x2.5x3.4xEBITDA to Int Exp7.9x8.6x7.6x6.8x7.0xEBITDA-CapEx to Interest-2.9x3.6x5.6x5.8x5.7xEBITDA Margin25.2%28.5%22.4%23.3%22.1%EBIT Margin19%22%15%15%18% Authoring (Author)Risks and CatalystsPROGRP guided to a mostly flat capex budget for the year (€305 million in FY19). Most of the spend will be related to the construction of the PM3 and the PW13. Construction of the PM3 remains on track and is expected to begin production as scheduled in 3Q20. We note that total capex for the project is now estimated to be approximately €465 million, which is up from its prior €375 million estimate.  As for the PW13, trial production has recently started, and the company expects to begin commercial production during the first quarter of 2020.  As highlighted on prior calls, the company expects to exceed its net leverage range of 2.5-3.0x as it continues to execute on its strategic expansion projects. Management expects to reach peak leverage by the end of the 2020, which should then fall back within its long-term range over the following 2-3 years.  Authoring (Author)Featured  Authoring (Author)Financial Condition€ mn4Q193Q192Q191Q19Corrugated Board Shipments308310307307Containerboard Shipments267267263259N/An/an/an/an/aCorrugated Board Shipment Growth YoY8.8%9.5%5.8%4.1%Containerboard Shipment Growth YoY7.7%13.6%10.2%(2.6%)N/An/an/an/an/a€ mnY19Y18Y17Y16Y15Short-Term Debt00000Long-Term Debt874678540459535Total Debt874678540459535Cash2031481183721Net Debt671530423421515Shareholder Equity395316277260209Market Capitalizationn/an/an/an/an/aEnterprise Value671530423421515EV / EBITDA3.0x1.9x2.3x2.5x3.4xFree cash flow, defined as EBITDA less capex and interest, was negative at (€37) million for the quarter. We note the elevated quarterly capex number, up from €46 million last year to €94 million, reflects the construction of PROGRP's new corrugated board lines and containerboard machine. The company ended the quarter with €874 million of total debt and €203 million of cash, bringing net leverage to 3.0x, up from 1.9x at prior year-end and 2.6x at 3Q19. We note that leverage currently sits at the high end of its target range of 2.5-3.0x. Authoring (Author)Operating Condition€ mnY19Y18Y17Y16EBITDA223275180171Cash Interest Payments(23)(50)(25)(26)CapEx(305)(159)(48)(23)Free Cash Flow(104)66107121Share Repurchases0000Dividends Paid(20)(87)(58)(6)Cash Taxes Payments(30)(34)(18)(13)Change in WC23(43)(35)18M&amp;A1000Net Free Cash Flow(130)(97)(3)120€ mn4Q193Q192Q191Q19EBITDA60425467Cash Interest Payments(3)(11)(7)(2)CapEx(94)(71)(68)(71)Free Cash Flow(37)(40)(21)(6)Share Repurchases0000Dividends Paid00(20)0Cash Taxes Payments(7)(6)(7)(9)Change in WC161222(26)M&amp;A0100Net Free Cash Flow(29)(33)(27)(41)Progroup reported 4Q19 sales of €206 million, down 12.9% from €237 million in 4Q18 and below our €230 million estimate. 4Q19 adjusted EBITDA was €60 million, down 17.8% from €73 million in the year-ago quarter yet ahead of our €56 million estimate. The decline this quarter reflects weaker containerboard prices as well as lower external containerboard sales volumes which fell 11.4% from 4Q18, mainly due to higher internal consumption. To the positive, however, the quarter recorded growth in overall containerboard volumes, up 7.7% YoY due to higher internal consumption (+10.8%). Also, corrugated board volumes were stronger for the period, up 8.8% YoY to 308,000 tonnes. Adjusted EBITDA margin was 29.0%, down from 31.0% in the year ago quarter yet was up from the 2019 low of 19.8% in 3Q19.</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cke_1_contents&quot;)/div[@class=&quot;cke_wysiwyg_div cke_reset cke_enable_context_menu cke_editable cke_editable_themed cke_contents_ltr quark-editor-content qxml-webkit&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cke_1_contents']/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remove Region'])[1]/following::div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keyboard shortcut Ctrl+Enter'])[1]/following::div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/div</value>
   </webElementXpaths>
</WebElementEntity>
